### PR TITLE
Merge floraxue repo 2

### PR DESCRIPTION
**Pull request by floraxue**
Modified version of merge-floraxue-repo branch. Took out the submit_answer endpoint stuffs.

### CODE REVIEW

**Comment by normangilmore** [comment]
@floraxue: Are these files relevant to the commit?

```
 CONTRIBUTING.md                |   83 +-
 README.md                      |  162 ++-
 app/assets/article_0_mock.json |   13 +
 app/assets/article_9_mock.json |   14 +
 app/assets/tua.json            | 2138 ++++++++++++++++++++++++++++++++++++++++
```

Also, this commit is already in master:
- Lexically sort schema file names to satisfy order dependencies.

If these files and the commit are extraneious, can you `git rebase --interactive` this branch with these removals and push it as merge-floraxue-repo-3?

**Comment by floraxue** [comment]
@normangilmore Changes in `CONTRIBUTING.md` is relevant. But where did you find the diff for the other 4 files? I didn't see them in the Files Changed section on Github.

**Comment by normangilmore** [comment]
I used the command `$ git diff-tree --stat master merge-floraxue-repo-2` but maybe that is not reflecting the same thing exactly as the PR. I'll look at it in a bit.

**Comment by normangilmore** [comment]
@floraxue I found my error. I should have done `git diff --stat master...merge-floraxue-repo-2`. Or, I could actually look at the github page for files changed in this PR. Sorry!

**Comment by floraxue** [comment]
@normangilmore No worries. I've made another branch without the "Lexically sort schema file names to satisfy order dependencies" commit. Going to close this one.

**Pull request closed without merging**
